# Generated by Django 3.1.1 on 2020-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('less5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('num_product', models.PositiveIntegerField(auto_created=True, null=True, unique=True, verbose_name='Номер продукта')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('productsname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=30, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тоовар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
        migrations.DeleteModel(
            name='РroductsModel',
        ),
    ]
