# Generated by Django 3.1.1 on 2020-10-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('less5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='РroductsModel',
            new_name='ProductModel',
        ),
    ]
