# Generated by Django 3.1.1 on 2020-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('less5', '0002_auto_20201025_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='deq',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
