# Generated by Django 3.1.1 on 2020-10-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('less5', '0002_auto_20201011_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='catid',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img',
        ),
    ]
